import {
  parseYouTubeVideoIdDetailed,
  type YouTubeUrlParseErrorCode,
} from "./url";

type CaptionTrack = {
  baseUrl: string;
  languageCode: string | null;
  isAutoGenerated: boolean;
};

export type TranscriptDiagnosticCode =
  | "invalid_url"
  | "video_id_missing"
  | "watch_page_fetch_failed"
  | "caption_tracks_missing"
  | "transcript_url_missing"
  | "transcript_fetch_failed"
  | "transcript_parse_failed"
  | "library_transcript_fetch_failed"
  | "library_transcript_parse_failed"
  | "custom_extractor_failed";

type TranscriptDiagnostic = {
  code: TranscriptDiagnosticCode;
  message: string;
};

type TranscriptSuccess = {
  ok: true;
  videoId: string;
  sourceText: string;
  languageCode: string | null;
  diagnostics: TranscriptDiagnostic[];
};

type TranscriptError = {
  ok: false;
  reason: "invalid_url" | "transcript_unavailable" | "transcript_fetch_failed";
  message: string;
  videoId?: string;
  diagnostics: TranscriptDiagnostic[];
};

export type YouTubeTranscriptResult = TranscriptSuccess | TranscriptError;

type TranscriptFetchResult =
  | { ok: true; text: string; languageCode: string | null }
  | { ok: false };

function mapUrlParseError(code: YouTubeUrlParseErrorCode): TranscriptDiagnosticCode {
  if (code === "invalid_url" || code === "unsupported_host") {
    return "invalid_url";
  }
  return "video_id_missing";
}

function decodeBaseUrl(value: string): string {
  return value.replace(/\\u0026/g, "&").replace(/&amp;/g, "&");
}

function decodeHtmlEntities(value: string): string {
  return value
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_, code: string) => {
      const number = Number(code);
      return Number.isFinite(number) ? String.fromCharCode(number) : "";
    });
}

function normalizeTranscriptText(text: string): string {
  return text
    .replace(/\r/g, " ")
    .replace(/\n/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function transcriptFromSegments(segments: Array<{ text?: string; lang?: string }>): {
  text: string;
  languageCode: string | null;
} | null {
  const chunks = segments
    .map((item) => (typeof item.text === "string" ? item.text : ""))
    .filter((item) => Boolean(item.trim()));

  if (chunks.length === 0) {
    return null;
  }

  const normalized = normalizeTranscriptText(chunks.join(" "));
  if (!normalized) {
    return null;
  }

  const languageCode =
    segments.find((item) => typeof item.lang === "string" && item.lang.trim())?.lang ??
    null;

  return { text: normalized, languageCode };
}

async function fetchTranscriptViaLibrary(
  videoId: string,
  diagnostics: TranscriptDiagnostic[]
): Promise<TranscriptFetchResult> {
  let fetchTranscriptFn: ((videoId: string, config?: { lang?: string }) => Promise<unknown>) | null =
    null;

  try {
    const lib = await import("youtube-transcript");
    if (typeof lib.fetchTranscript === "function") {
      fetchTranscriptFn = lib.fetchTranscript as (
        videoId: string,
        config?: { lang?: string }
      ) => Promise<unknown>;
    }
  } catch {
    diagnostics.push({
      code: "library_transcript_fetch_failed",
      message: "Transcript library could not be loaded.",
    });
    return { ok: false };
  }

  if (!fetchTranscriptFn) {
    diagnostics.push({
      code: "library_transcript_fetch_failed",
      message: "Transcript library does not expose fetchTranscript.",
    });
    return { ok: false };
  }

  const attempts: Array<{ lang?: string; label: string }> = [
    { lang: "en", label: "library:en" },
    { label: "library:any" },
  ];

  for (const attempt of attempts) {
    try {
      const response = (await fetchTranscriptFn(videoId, {
        ...(attempt.lang ? { lang: attempt.lang } : {}),
      })) as unknown;

      if (!Array.isArray(response)) {
        diagnostics.push({
          code: "library_transcript_parse_failed",
          message: `${attempt.label} returned a non-array transcript payload.`,
        });
        continue;
      }

      const parsed = transcriptFromSegments(
        response.filter((item): item is { text?: string; lang?: string } => {
          return Boolean(item && typeof item === "object");
        })
      );

      if (parsed) {
        return {
          ok: true,
          text: parsed.text,
          languageCode: parsed.languageCode,
        };
      }

      diagnostics.push({
        code: "library_transcript_parse_failed",
        message: `${attempt.label} returned empty transcript text.`,
      });
    } catch (error) {
      diagnostics.push({
        code: "library_transcript_fetch_failed",
        message: `${attempt.label} failed: ${
          error instanceof Error ? error.message : "unknown error"
        }`,
      });
    }
  }

  return { ok: false };
}

function extractBalancedSegment(
  source: string,
  startIndex: number,
  openChar: "{" | "[",
  closeChar: "}" | "]"
): string | null {
  if (
    startIndex < 0 ||
    startIndex >= source.length ||
    source[startIndex] !== openChar
  ) {
    return null;
  }

  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let i = startIndex; i < source.length; i += 1) {
    const char = source[i];

    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === '"') {
        inString = false;
      }
      continue;
    }

    if (char === '"') {
      inString = true;
      continue;
    }

    if (char === openChar) {
      depth += 1;
      continue;
    }

    if (char === closeChar) {
      depth -= 1;
      if (depth === 0) {
        return source.slice(startIndex, i + 1);
      }
    }
  }

  return null;
}

function extractJsonArrayAfterToken(source: string, token: string): string | null {
  const tokenIndex = source.indexOf(token);
  if (tokenIndex === -1) return null;
  const startIndex = source.indexOf("[", tokenIndex + token.length);
  return extractBalancedSegment(source, startIndex, "[", "]");
}

function extractJsonObjectAfterToken(source: string, token: string): string | null {
  const tokenIndex = source.indexOf(token);
  if (tokenIndex === -1) return null;
  const startIndex = source.indexOf("{", tokenIndex + token.length);
  return extractBalancedSegment(source, startIndex, "{", "}");
}

function findCaptionTracksInObject(value: unknown): unknown[] {
  if (!value || typeof value !== "object") {
    return [];
  }

  const root = value as Record<string, unknown>;

  const tracksDirect = (root as { captionTracks?: unknown }).captionTracks;
  if (Array.isArray(tracksDirect)) {
    return tracksDirect;
  }

  const nested =
    (root as {
      captions?: {
        playerCaptionsTracklistRenderer?: { captionTracks?: unknown };
      };
    }).captions?.playerCaptionsTracklistRenderer?.captionTracks;

  if (Array.isArray(nested)) {
    return nested;
  }

  for (const child of Object.values(root)) {
    const found = findCaptionTracksInObject(child);
    if (found.length > 0) {
      return found;
    }
  }

  return [];
}

function normalizeCaptionTracks(rawTracks: unknown[]): CaptionTrack[] {
  return rawTracks
    .filter((entry): entry is Record<string, unknown> => {
      return Boolean(entry && typeof entry === "object");
    })
    .map((entry) => {
      const trackRoot =
        entry.captionTrackRenderer && typeof entry.captionTrackRenderer === "object"
          ? (entry.captionTrackRenderer as Record<string, unknown>)
          : entry;

      const languageCode =
        typeof trackRoot.languageCode === "string" ? trackRoot.languageCode : null;
      const kind = typeof trackRoot.kind === "string" ? trackRoot.kind : "";
      const baseUrl =
        typeof trackRoot.baseUrl === "string" ? decodeBaseUrl(trackRoot.baseUrl) : "";

      return {
        baseUrl,
        languageCode,
        isAutoGenerated: kind === "asr",
      } satisfies CaptionTrack;
    })
    .filter((track) => Boolean(track.baseUrl));
}

function parseCaptionTracksFromWatchHtml(html: string): CaptionTrack[] {
  const rawTrackCandidates: unknown[][] = [];

  const fromToken = extractJsonArrayAfterToken(html, '"captionTracks":');
  if (fromToken) {
    try {
      const parsed = JSON.parse(fromToken) as unknown;
      if (Array.isArray(parsed)) {
        rawTrackCandidates.push(parsed);
      }
    } catch {
      // continue with other extraction paths
    }
  }

  const playerResponseTokens = [
    "var ytInitialPlayerResponse = ",
    'window["ytInitialPlayerResponse"] = ',
    "ytInitialPlayerResponse = ",
  ];

  for (const token of playerResponseTokens) {
    const rawObject = extractJsonObjectAfterToken(html, token);
    if (!rawObject) continue;
    try {
      const parsed = JSON.parse(rawObject) as unknown;
      const found = findCaptionTracksInObject(parsed);
      if (found.length > 0) {
        rawTrackCandidates.push(found);
      }
    } catch {
      // continue
    }
  }

  const normalized = rawTrackCandidates.flatMap((candidate) =>
    normalizeCaptionTracks(candidate)
  );

  const deduped = new Map<string, CaptionTrack>();
  for (const track of normalized) {
    if (!deduped.has(track.baseUrl)) {
      deduped.set(track.baseUrl, track);
    }
  }

  return Array.from(deduped.values());
}

function prioritizeTracks(tracks: CaptionTrack[]): CaptionTrack[] {
  return [...tracks].sort((a, b) => {
    const aIsEnglish = (a.languageCode || "").toLowerCase().startsWith("en");
    const bIsEnglish = (b.languageCode || "").toLowerCase().startsWith("en");
    if (aIsEnglish !== bIsEnglish) return aIsEnglish ? -1 : 1;

    if (a.isAutoGenerated !== b.isAutoGenerated) {
      return a.isAutoGenerated ? 1 : -1;
    }

    return 0;
  });
}

async function fetchWatchPage(videoId: string): Promise<string | null> {
  const urls = [
    `https://www.youtube.com/watch?v=${videoId}&hl=en`,
    `https://m.youtube.com/watch?v=${videoId}&hl=en`,
  ];

  for (const url of urls) {
    try {
      const response = await fetch(url, { cache: "no-store" });
      if (!response.ok) {
        continue;
      }
      const html = await response.text();
      if (html && html.length > 0) {
        return html;
      }
    } catch {
      // try next
    }
  }

  return null;
}

async function fetchJson(url: string): Promise<{ ok: true; data: unknown } | { ok: false }> {
  try {
    const response = await fetch(url, { cache: "no-store" });
    if (!response.ok) {
      return { ok: false };
    }
    const data = (await response.json()) as unknown;
    return { ok: true, data };
  } catch {
    return { ok: false };
  }
}

async function fetchText(url: string): Promise<{ ok: true; text: string } | { ok: false }> {
  try {
    const response = await fetch(url, { cache: "no-store" });
    if (!response.ok) return { ok: false };
    return { ok: true, text: await response.text() };
  } catch {
    return { ok: false };
  }
}

function parseTranscriptFromJson3(data: unknown): string | null {
  if (!data || typeof data !== "object") return null;
  const events = (data as { events?: unknown }).events;
  if (!Array.isArray(events)) return null;

  const chunks: string[] = [];
  for (const event of events) {
    if (!event || typeof event !== "object") continue;
    const segs = (event as { segs?: unknown }).segs;
    if (!Array.isArray(segs)) continue;

    for (const segment of segs) {
      if (!segment || typeof segment !== "object") continue;
      const utf8 = (segment as { utf8?: unknown }).utf8;
      if (typeof utf8 === "string" && utf8.trim()) {
        chunks.push(decodeHtmlEntities(utf8));
      }
    }
  }

  if (chunks.length === 0) return null;
  return normalizeTranscriptText(chunks.join(" "));
}

function parseTranscriptFromXml(xml: string): string | null {
  const matches = xml.matchAll(/<text\b[^>]*>([\s\S]*?)<\/text>/g);
  const chunks: string[] = [];
  for (const match of matches) {
    const value = match[1] ? decodeHtmlEntities(match[1]) : "";
    if (value.trim()) chunks.push(value);
  }
  if (chunks.length === 0) return null;
  return normalizeTranscriptText(chunks.join(" "));
}

function appendFmtJson3(url: string): string {
  if (url.includes("fmt=json3")) return url;
  return `${url}${url.includes("?") ? "&" : "?"}fmt=json3`;
}

function stripFmtJson3(url: string): string {
  return url
    .replace(/([?&])fmt=json3(&?)/, (_, prefix: string, suffix: string) =>
      suffix ? prefix : ""
    )
    .replace(/[?&]$/, "");
}

async function fetchTranscriptFromTrack(
  track: CaptionTrack
): Promise<
  | { ok: true; text: string; languageCode: string | null }
  | { ok: false; code: "transcript_fetch_failed" | "transcript_parse_failed" }
> {
  if (!track.baseUrl) {
    return { ok: false, code: "transcript_fetch_failed" };
  }

  const jsonResponse = await fetchJson(appendFmtJson3(track.baseUrl));
  if (jsonResponse.ok) {
    const parsed = parseTranscriptFromJson3(jsonResponse.data);
    if (parsed) {
      return { ok: true, text: parsed, languageCode: track.languageCode };
    }
  }

  const xmlResponse = await fetchText(stripFmtJson3(track.baseUrl));
  if (!xmlResponse.ok) {
    return { ok: false, code: "transcript_fetch_failed" };
  }

  const parsedXml = parseTranscriptFromXml(xmlResponse.text);
  if (!parsedXml) {
    return { ok: false, code: "transcript_parse_failed" };
  }

  return { ok: true, text: parsedXml, languageCode: track.languageCode };
}

function buildTimedTextFallbacks(videoId: string): CaptionTrack[] {
  const urls = [
    { lang: "en", kind: "manual", url: `https://www.youtube.com/api/timedtext?v=${videoId}&lang=en` },
    { lang: "en-US", kind: "manual", url: `https://www.youtube.com/api/timedtext?v=${videoId}&lang=en-US` },
    { lang: "en", kind: "asr", url: `https://www.youtube.com/api/timedtext?v=${videoId}&lang=en&kind=asr` },
    { lang: "en", kind: "manual", url: `https://video.google.com/timedtext?v=${videoId}&lang=en` },
    { lang: "en-US", kind: "manual", url: `https://video.google.com/timedtext?v=${videoId}&lang=en-US` },
  ];

  return urls.map((entry) => ({
    baseUrl: entry.url,
    languageCode: entry.lang,
    isAutoGenerated: entry.kind === "asr",
  }));
}

async function fetchTranscriptViaCustomExtractor(
  videoId: string,
  diagnostics: TranscriptDiagnostic[]
): Promise<TranscriptFetchResult> {
  const watchHtml = await fetchWatchPage(videoId);
  if (!watchHtml) {
    diagnostics.push({
      code: "watch_page_fetch_failed",
      message: "Could not fetch YouTube watch page.",
    });
  }

  const parsedTracks = watchHtml ? parseCaptionTracksFromWatchHtml(watchHtml) : [];
  if (parsedTracks.length === 0) {
    diagnostics.push({
      code: "caption_tracks_missing",
      message: "No caption tracks were discovered in watch page payloads.",
    });
  }

  const candidateTracks = [
    ...prioritizeTracks(parsedTracks),
    ...prioritizeTracks(buildTimedTextFallbacks(videoId)),
  ];

  const seenTrackUrls = new Set<string>();
  const uniqueTracks = candidateTracks.filter((track) => {
    if (!track.baseUrl) return false;
    if (seenTrackUrls.has(track.baseUrl)) return false;
    seenTrackUrls.add(track.baseUrl);
    return true;
  });

  if (uniqueTracks.length === 0) {
    diagnostics.push({
      code: "transcript_url_missing",
      message: "No transcript URL candidates were available.",
    });
    diagnostics.push({
      code: "custom_extractor_failed",
      message: "Custom extractor had no usable transcript URL candidates.",
    });
    return { ok: false };
  }

  let sawFetchFailure = false;
  let sawParseFailure = false;

  for (const track of uniqueTracks) {
    const transcript = await fetchTranscriptFromTrack(track);
    if (transcript.ok) {
      return {
        ok: true,
        text: transcript.text,
        languageCode: transcript.languageCode,
      };
    }

    if (transcript.code === "transcript_fetch_failed") {
      sawFetchFailure = true;
    }
    if (transcript.code === "transcript_parse_failed") {
      sawParseFailure = true;
    }
  }

  if (sawFetchFailure) {
    diagnostics.push({
      code: "transcript_fetch_failed",
      message: "Transcript track requests failed in custom extractor.",
    });
  }

  if (sawParseFailure) {
    diagnostics.push({
      code: "transcript_parse_failed",
      message: "Transcript payloads were fetched but could not be parsed.",
    });
  }

  diagnostics.push({
    code: "custom_extractor_failed",
    message: "Custom extractor did not resolve a usable transcript.",
  });

  return { ok: false };
}

export async function fetchYouTubeTranscriptSource(
  sourceUrl: string
): Promise<YouTubeTranscriptResult> {
  const diagnostics: TranscriptDiagnostic[] = [];

  const parsed = parseYouTubeVideoIdDetailed(sourceUrl);
  if (!parsed.ok) {
    diagnostics.push({
      code: mapUrlParseError(parsed.code),
      message: `URL parse failure: ${parsed.code}`,
    });

    return {
      ok: false,
      reason: "invalid_url",
      message: "Invalid YouTube URL.",
      diagnostics,
    };
  }

  const { videoId } = parsed;

  const libraryResult = await fetchTranscriptViaLibrary(videoId, diagnostics);
  if (libraryResult.ok) {
    return {
      ok: true,
      videoId,
      sourceText: libraryResult.text,
      languageCode: libraryResult.languageCode,
      diagnostics,
    };
  }

  const customResult = await fetchTranscriptViaCustomExtractor(videoId, diagnostics);
  if (customResult.ok) {
    return {
      ok: true,
      videoId,
      sourceText: customResult.text,
      languageCode: customResult.languageCode,
      diagnostics,
    };
  }

  return {
    ok: false,
    reason: "transcript_unavailable",
    message: "Transcript unavailable for this video.",
    videoId,
    diagnostics,
  };
}
