import {
  parseYouTubeVideoIdDetailed,
  type YouTubeUrlParseErrorCode,
} from "./url";

type CaptionTrack = {
  baseUrl: string;
  languageCode: string | null;
  isAutoGenerated: boolean;
};

export type TranscriptFailureReason =
  | "invalid_url"
  | "no_captions"
  | "captions_disabled"
  | "transcript_fetch_failed"
  | "unsupported_video"
  | "unknown_error";

export type TranscriptDiagnosticCode =
  | "invalid_url"
  | "video_id_missing"
  | "unsupported_video"
  | "captions_disabled"
  | "no_captions"
  | "watch_page_fetch_failed"
  | "caption_tracks_missing"
  | "transcript_url_missing"
  | "transcript_fetch_failed"
  | "transcript_parse_failed"
  | "library_transcript_fetch_failed"
  | "library_transcript_parse_failed"
  | "custom_extractor_failed";

type TranscriptDiagnostic = {
  code: TranscriptDiagnosticCode;
  message: string;
};

type TranscriptSuccess = {
  ok: true;
  videoId: string;
  sourceText: string;
  languageCode: string | null;
  diagnostics: TranscriptDiagnostic[];
};

type TranscriptError = {
  ok: false;
  reason: TranscriptFailureReason;
  message: string;
  videoId?: string;
  diagnostics: TranscriptDiagnostic[];
};

export type YouTubeTranscriptResult = TranscriptSuccess | TranscriptError;

type TranscriptFetchResult =
  | { ok: true; text: string; languageCode: string | null }
  | { ok: false; reason?: Exclude<TranscriptFailureReason, "invalid_url"> };

const USER_AGENT =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
const YOUTUBE_ORIGIN = "https://www.youtube.com";
const YOUTUBE_REFERER = "https://www.youtube.com/";
const BROWSER_HEADERS = {
  "User-Agent": USER_AGENT,
  "Accept-Language": "en-US,en;q=0.9",
  Referer: YOUTUBE_REFERER,
  Origin: YOUTUBE_ORIGIN,
  Accept:
    "text/html,application/xhtml+xml,application/xml;q=0.9,application/json;q=0.8,*/*;q=0.7",
} satisfies Record<string, string>;

const INNERTUBE_CLIENTS = [
  {
    label: "innertube:android",
    context: {
      client: {
        clientName: "ANDROID",
        clientVersion: "20.10.38",
        androidSdkVersion: 35,
      },
    },
    headers: {
      "User-Agent": "com.google.android.youtube/20.10.38 (Linux; U; Android 14)",
      "Accept-Language": "en-US,en;q=0.9",
      Referer: YOUTUBE_REFERER,
      Origin: YOUTUBE_ORIGIN,
    },
  },
  {
    label: "innertube:web",
    context: {
      client: {
        clientName: "WEB",
        clientVersion: "2.20240101.00.00",
        hl: "en",
        gl: "US",
      },
    },
    headers: {
      ...BROWSER_HEADERS,
    },
  },
] as const;

function logTranscriptDebug(stage: string, details: Record<string, unknown>) {
  console.info(`[youtube-transcript] ${stage}`, details);
}

function normalizeHeaders(headers: HeadersInit | undefined): Record<string, string> {
  if (!headers) return {};
  if (headers instanceof Headers) {
    return Object.fromEntries(headers.entries());
  }
  if (Array.isArray(headers)) {
    return Object.fromEntries(headers);
  }
  return headers;
}

function withYouTubeHeaders(
  headers?: HeadersInit,
  overrides: Record<string, string> = {}
): Record<string, string> {
  return {
    ...BROWSER_HEADERS,
    ...normalizeHeaders(headers),
    ...overrides,
  };
}

const browserFetch: typeof fetch = (input, init = {}) => {
  return fetch(input, {
    ...init,
    headers: withYouTubeHeaders(init.headers),
  });
};

function mapUrlParseError(code: YouTubeUrlParseErrorCode): TranscriptDiagnosticCode {
  if (code === "invalid_url" || code === "unsupported_host") {
    return "invalid_url";
  }
  return "video_id_missing";
}

function decodeBaseUrl(value: string): string {
  return value.replace(/\\u0026/g, "&").replace(/&amp;/g, "&");
}

function decodeHtmlEntities(value: string): string {
  return value
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_, code: string) => {
      const number = Number(code);
      return Number.isFinite(number) ? String.fromCharCode(number) : "";
    });
}

function normalizeTranscriptText(text: string): string {
  return text
    .replace(/\r/g, " ")
    .replace(/\n/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function transcriptFromSegments(segments: Array<{ text?: string; lang?: string }>): {
  text: string;
  languageCode: string | null;
} | null {
  const chunks = segments
    .map((item) => (typeof item.text === "string" ? item.text : ""))
    .filter((item) => Boolean(item.trim()));

  if (chunks.length === 0) {
    return null;
  }

  const normalized = normalizeTranscriptText(chunks.join(" "));
  if (!normalized) {
    return null;
  }

  const languageCode =
    segments.find((item) => typeof item.lang === "string" && item.lang.trim())?.lang ??
    null;

  return { text: normalized, languageCode };
}

async function fetchTranscriptViaSupadata(
  videoId: string,
  diagnostics: TranscriptDiagnostic[]
): Promise<TranscriptFetchResult> {
  const apiKey = process.env.SUPADATA_API_KEY || "";
  if (!apiKey) {
    logTranscriptDebug("supadata.no_api_key", { videoId });
    return { ok: false };
  }

  const requestUrl = `https://api.supadata.ai/v1/transcript?url=https://www.youtube.com/watch?v=${videoId}&text=true`;
  logTranscriptDebug("supadata.request", { videoId });

  try {
    const response = await fetch(requestUrl, {
      cache: "no-store",
      next: { revalidate: 0 },
      headers: {
        "x-api-key": apiKey,
        Accept: "application/json",
      },
    } as RequestInit & { next: { revalidate: number } });

    if (!response.ok) {
      const body = await response.text().catch(() => "");
      logTranscriptDebug("supadata.http_failed", {
        videoId,
        status: response.status,
        body: body.slice(0, 500),
      });
      diagnostics.push({
        code: "transcript_fetch_failed",
        message: `Supadata transcript request failed with HTTP ${response.status}.`,
      });
      return { ok: false, reason: "transcript_fetch_failed" };
    }

    const data = (await response.json().catch(() => null)) as
      | {
          content?: unknown;
          language?: unknown;
          lang?: unknown;
          languageCode?: unknown;
        }
      | null;
    const content = Array.isArray(data?.content) ? data.content : [];
    const chunks = content
      .map((item) => {
        if (!item || typeof item !== "object") return "";
        const text = (item as { text?: unknown }).text;
        return typeof text === "string" ? text : "";
      })
      .filter((text) => Boolean(text.trim()));
    const text = normalizeTranscriptText(chunks.join(" "));

    if (!text) {
      logTranscriptDebug("supadata.empty_response", {
        videoId,
        contentItems: content.length,
      });
      diagnostics.push({
        code: "no_captions",
        message: "Supadata returned no transcript text.",
      });
      return { ok: false, reason: "no_captions" };
    }

    const chunkLanguage = content.find((item) => {
      if (!item || typeof item !== "object") return false;
      const lang = (item as { lang?: unknown; language?: unknown }).lang;
      const language = (item as { lang?: unknown; language?: unknown }).language;
      return (
        (typeof lang === "string" && Boolean(lang.trim())) ||
        (typeof language === "string" && Boolean(language.trim()))
      );
    }) as { lang?: unknown; language?: unknown } | undefined;
    const languageCode =
      typeof data?.languageCode === "string" && data.languageCode.trim()
        ? data.languageCode
        : typeof data?.language === "string" && data.language.trim()
          ? data.language
          : typeof data?.lang === "string" && data.lang.trim()
            ? data.lang
            : typeof chunkLanguage?.lang === "string" && chunkLanguage.lang.trim()
              ? chunkLanguage.lang
              : typeof chunkLanguage?.language === "string" &&
                  chunkLanguage.language.trim()
                ? chunkLanguage.language
                : null;

    logTranscriptDebug("supadata.success", {
      videoId,
      languageCode,
      textLength: text.length,
      contentItems: content.length,
    });

    return { ok: true, text, languageCode };
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "Unknown Supadata transcript error.";
    logTranscriptDebug("supadata.failed", { videoId, error: message });
    diagnostics.push({
      code: "transcript_fetch_failed",
      message: `Supadata transcript request failed: ${message}`,
    });
    return { ok: false, reason: "transcript_fetch_failed" };
  }
}

function classifyErrorMessage(message: string): Exclude<TranscriptFailureReason, "invalid_url"> {
  const lower = message.toLowerCase();

  if (
    lower.includes("disabled") ||
    lower.includes("transcript is disabled") ||
    lower.includes("captions are disabled")
  ) {
    return "captions_disabled";
  }

  if (
    lower.includes("no transcripts") ||
    lower.includes("not available") ||
    lower.includes("no captions") ||
    lower.includes("caption tracks") ||
    lower.includes("available languages")
  ) {
    return "no_captions";
  }

  if (
    lower.includes("video unavailable") ||
    lower.includes("no longer available") ||
    lower.includes("private") ||
    lower.includes("members-only") ||
    lower.includes("age-restricted") ||
    lower.includes("sign in")
  ) {
    return "unsupported_video";
  }

  if (
    lower.includes("too many requests") ||
    lower.includes("captcha") ||
    lower.includes("fetch failed") ||
    lower.includes("network") ||
    lower.includes("timeout")
  ) {
    return "transcript_fetch_failed";
  }

  return "unknown_error";
}

async function fetchTranscriptViaLibrary(
  videoId: string,
  diagnostics: TranscriptDiagnostic[]
): Promise<TranscriptFetchResult> {
  let fetchTranscriptFn:
    | ((
        videoId: string,
        config?: { lang?: string; fetch?: typeof fetch }
      ) => Promise<unknown>)
    | null = null;

  try {
    const lib = await import("youtube-transcript");
    if (typeof lib.fetchTranscript === "function") {
      fetchTranscriptFn = lib.fetchTranscript as (
        videoId: string,
        config?: { lang?: string; fetch?: typeof fetch }
      ) => Promise<unknown>;
    } else if (
      lib.YoutubeTranscript &&
      typeof lib.YoutubeTranscript.fetchTranscript === "function"
    ) {
      fetchTranscriptFn = lib.YoutubeTranscript.fetchTranscript.bind(
        lib.YoutubeTranscript
      ) as (
        videoId: string,
        config?: { lang?: string; fetch?: typeof fetch }
      ) => Promise<unknown>;
    }
  } catch {
    logTranscriptDebug("library.load_failed", { videoId });
    diagnostics.push({
      code: "library_transcript_fetch_failed",
      message: "Transcript library could not be loaded.",
    });
    return { ok: false };
  }

  if (!fetchTranscriptFn) {
    logTranscriptDebug("library.missing_export", { videoId });
    diagnostics.push({
      code: "library_transcript_fetch_failed",
      message: "Transcript library does not expose fetchTranscript.",
    });
    return { ok: false };
  }

  const attempts: Array<{ lang?: string; label: string }> = [
    { lang: "en", label: "library:en" },
    { label: "library:any" },
  ];

  for (const attempt of attempts) {
    try {
      const response = (await fetchTranscriptFn(videoId, {
        ...(attempt.lang ? { lang: attempt.lang } : {}),
        fetch: browserFetch,
      })) as unknown;

      if (!Array.isArray(response)) {
        logTranscriptDebug("library.non_array_response", {
          videoId,
          attempt: attempt.label,
        });
        diagnostics.push({
          code: "library_transcript_parse_failed",
          message: `${attempt.label} returned a non-array transcript payload.`,
        });
        continue;
      }

      const parsed = transcriptFromSegments(
        response.filter((item): item is { text?: string; lang?: string } => {
          return Boolean(item && typeof item === "object");
        })
      );

      if (parsed) {
        logTranscriptDebug("library.success", {
          videoId,
          attempt: attempt.label,
          languageCode: parsed.languageCode,
          textLength: parsed.text.length,
        });
        return {
          ok: true,
          text: parsed.text,
          languageCode: parsed.languageCode,
        };
      }

      diagnostics.push({
        code: "library_transcript_parse_failed",
        message: `${attempt.label} returned empty transcript text.`,
      });
      logTranscriptDebug("library.empty_transcript", {
        videoId,
        attempt: attempt.label,
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : "unknown error";
      logTranscriptDebug("library.failed", {
        videoId,
        attempt: attempt.label,
        message,
      });
      diagnostics.push({
        code: "library_transcript_fetch_failed",
        message: `${attempt.label} failed: ${message}`,
      });
    }
  }

  const classified = diagnostics
    .filter((item) => item.code === "library_transcript_fetch_failed")
    .map((item) => classifyErrorMessage(item.message))
    .find((reason) => reason !== "unknown_error");

  const reason = classified ?? "unknown_error";
  logTranscriptDebug("library.exhausted", { videoId, reason });
  return { ok: false, reason };
}

function extractBalancedSegment(
  source: string,
  startIndex: number,
  openChar: "{" | "[",
  closeChar: "}" | "]"
): string | null {
  if (
    startIndex < 0 ||
    startIndex >= source.length ||
    source[startIndex] !== openChar
  ) {
    return null;
  }

  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let i = startIndex; i < source.length; i += 1) {
    const char = source[i];

    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === '"') {
        inString = false;
      }
      continue;
    }

    if (char === '"') {
      inString = true;
      continue;
    }

    if (char === openChar) {
      depth += 1;
      continue;
    }

    if (char === closeChar) {
      depth -= 1;
      if (depth === 0) {
        return source.slice(startIndex, i + 1);
      }
    }
  }

  return null;
}

function extractJsonArrayAfterToken(source: string, token: string): string | null {
  const tokenIndex = source.indexOf(token);
  if (tokenIndex === -1) return null;
  const startIndex = source.indexOf("[", tokenIndex + token.length);
  return extractBalancedSegment(source, startIndex, "[", "]");
}

function extractJsonObjectAfterToken(source: string, token: string): string | null {
  const tokenIndex = source.indexOf(token);
  if (tokenIndex === -1) return null;
  const startIndex = source.indexOf("{", tokenIndex + token.length);
  return extractBalancedSegment(source, startIndex, "{", "}");
}

function findCaptionTracksInObject(value: unknown): unknown[] {
  if (!value || typeof value !== "object") {
    return [];
  }

  const root = value as Record<string, unknown>;

  const tracksDirect = (root as { captionTracks?: unknown }).captionTracks;
  if (Array.isArray(tracksDirect)) {
    return tracksDirect;
  }

  const nested =
    (root as {
      captions?: {
        playerCaptionsTracklistRenderer?: { captionTracks?: unknown };
      };
    }).captions?.playerCaptionsTracklistRenderer?.captionTracks;

  if (Array.isArray(nested)) {
    return nested;
  }

  for (const child of Object.values(root)) {
    const found = findCaptionTracksInObject(child);
    if (found.length > 0) {
      return found;
    }
  }

  return [];
}

function findPlayabilityStatusInObject(value: unknown): Record<string, unknown> | null {
  if (!value || typeof value !== "object") {
    return null;
  }

  const root = value as Record<string, unknown>;
  const direct = root.playabilityStatus;
  if (direct && typeof direct === "object") {
    return direct as Record<string, unknown>;
  }

  for (const child of Object.values(root)) {
    const found = findPlayabilityStatusInObject(child);
    if (found) return found;
  }

  return null;
}

function normalizeCaptionTracks(rawTracks: unknown[]): CaptionTrack[] {
  return rawTracks
    .filter((entry): entry is Record<string, unknown> => {
      return Boolean(entry && typeof entry === "object");
    })
    .map((entry) => {
      const trackRoot =
        entry.captionTrackRenderer && typeof entry.captionTrackRenderer === "object"
          ? (entry.captionTrackRenderer as Record<string, unknown>)
          : entry;

      const languageCode =
        typeof trackRoot.languageCode === "string" ? trackRoot.languageCode : null;
      const kind = typeof trackRoot.kind === "string" ? trackRoot.kind : "";
      const baseUrl =
        typeof trackRoot.baseUrl === "string" ? decodeBaseUrl(trackRoot.baseUrl) : "";

      return {
        baseUrl,
        languageCode,
        isAutoGenerated: kind === "asr",
      } satisfies CaptionTrack;
    })
    .filter((track) => Boolean(track.baseUrl));
}

function parseCaptionTracksFromWatchHtml(html: string): CaptionTrack[] {
  const rawTrackCandidates: unknown[][] = [];

  const fromToken = extractJsonArrayAfterToken(html, '"captionTracks":');
  if (fromToken) {
    try {
      const parsed = JSON.parse(fromToken) as unknown;
      if (Array.isArray(parsed)) {
        rawTrackCandidates.push(parsed);
      }
    } catch {
      // continue with other extraction paths
    }
  }

  const playerResponseTokens = [
    "var ytInitialPlayerResponse = ",
    'window["ytInitialPlayerResponse"] = ',
    "ytInitialPlayerResponse = ",
  ];

  for (const token of playerResponseTokens) {
    const rawObject = extractJsonObjectAfterToken(html, token);
    if (!rawObject) continue;
    try {
      const parsed = JSON.parse(rawObject) as unknown;
      const found = findCaptionTracksInObject(parsed);
      if (found.length > 0) {
        rawTrackCandidates.push(found);
      }
    } catch {
      // continue
    }
  }

  const normalized = rawTrackCandidates.flatMap((candidate) =>
    normalizeCaptionTracks(candidate)
  );

  const deduped = new Map<string, CaptionTrack>();
  for (const track of normalized) {
    if (!deduped.has(track.baseUrl)) {
      deduped.set(track.baseUrl, track);
    }
  }

  return Array.from(deduped.values());
}

function parsePlayerResponsesFromWatchHtml(html: string): unknown[] {
  const responses: unknown[] = [];
  const playerResponseTokens = [
    "var ytInitialPlayerResponse = ",
    'window["ytInitialPlayerResponse"] = ',
    "ytInitialPlayerResponse = ",
  ];

  for (const token of playerResponseTokens) {
    const rawObject = extractJsonObjectAfterToken(html, token);
    if (!rawObject) continue;
    try {
      responses.push(JSON.parse(rawObject) as unknown);
    } catch {
      // continue
    }
  }

  return responses;
}

function classifyWatchHtmlFailure(html: string): Exclude<TranscriptFailureReason, "invalid_url"> | null {
  if (html.includes('class="g-recaptcha"') || html.includes("captcha")) {
    return "transcript_fetch_failed";
  }

  const responses = parsePlayerResponsesFromWatchHtml(html);
  for (const response of responses) {
    const status = findPlayabilityStatusInObject(response);
    if (!status) continue;
    const rawStatus = typeof status.status === "string" ? status.status.toLowerCase() : "";
    const reason = typeof status.reason === "string" ? status.reason : "";
    const combined = `${rawStatus} ${reason}`.toLowerCase();

    if (
      rawStatus === "error" ||
      rawStatus === "login_required" ||
      combined.includes("private") ||
      combined.includes("unavailable") ||
      combined.includes("age") ||
      combined.includes("sign in")
    ) {
      return "unsupported_video";
    }
  }

  return null;
}

function prioritizeTracks(tracks: CaptionTrack[]): CaptionTrack[] {
  return [...tracks].sort((a, b) => {
    const aIsEnglish = (a.languageCode || "").toLowerCase().startsWith("en");
    const bIsEnglish = (b.languageCode || "").toLowerCase().startsWith("en");
    if (aIsEnglish !== bIsEnglish) return aIsEnglish ? -1 : 1;

    if (a.isAutoGenerated !== b.isAutoGenerated) {
      return a.isAutoGenerated ? 1 : -1;
    }

    return 0;
  });
}

async function fetchWatchPage(videoId: string): Promise<string | null> {
  const urls = [
    `https://www.youtube.com/watch?v=${videoId}&hl=en`,
    `https://m.youtube.com/watch?v=${videoId}&hl=en`,
  ];

  for (const url of urls) {
    try {
      const response = await fetch(url, {
        cache: "no-store",
        headers: withYouTubeHeaders(undefined, {
          Accept:
            "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        }),
      });
      if (!response.ok) {
        logTranscriptDebug("watch_page.http_failed", {
          videoId,
          url,
          status: response.status,
        });
        continue;
      }
      const html = await response.text();
      if (html && html.length > 0) {
        logTranscriptDebug("watch_page.success", {
          videoId,
          url,
          htmlLength: html.length,
        });
        return html;
      }
      logTranscriptDebug("watch_page.empty", { videoId, url });
    } catch {
      logTranscriptDebug("watch_page.fetch_failed", { videoId, url });
      // try next
    }
  }

  return null;
}

async function fetchJson(url: string): Promise<{ ok: true; data: unknown } | { ok: false }> {
  try {
    const response = await fetch(url, {
      cache: "no-store",
      headers: withYouTubeHeaders(undefined, {
        Accept: "application/json,text/plain,*/*",
      }),
    });
    if (!response.ok) {
      logTranscriptDebug("caption_json.http_failed", {
        url,
        status: response.status,
      });
      return { ok: false };
    }
    const data = (await response.json()) as unknown;
    return { ok: true, data };
  } catch (error) {
    logTranscriptDebug("caption_json.fetch_failed", {
      url,
      message: error instanceof Error ? error.message : "unknown error",
    });
    return { ok: false };
  }
}

async function fetchText(url: string): Promise<{ ok: true; text: string } | { ok: false }> {
  try {
    const response = await fetch(url, {
      cache: "no-store",
      headers: withYouTubeHeaders(undefined, {
        Accept: "text/xml,application/xml,text/plain,*/*",
      }),
    });
    if (!response.ok) {
      logTranscriptDebug("caption_text.http_failed", {
        url,
        status: response.status,
      });
      return { ok: false };
    }
    const text = await response.text();
    return { ok: true, text };
  } catch (error) {
    logTranscriptDebug("caption_text.fetch_failed", {
      url,
      message: error instanceof Error ? error.message : "unknown error",
    });
    return { ok: false };
  }
}

function parseTranscriptFromJson3(data: unknown): string | null {
  if (!data || typeof data !== "object") return null;
  const events = (data as { events?: unknown }).events;
  if (!Array.isArray(events)) return null;

  const chunks: string[] = [];
  for (const event of events) {
    if (!event || typeof event !== "object") continue;
    const segs = (event as { segs?: unknown }).segs;
    if (!Array.isArray(segs)) continue;

    for (const segment of segs) {
      if (!segment || typeof segment !== "object") continue;
      const utf8 = (segment as { utf8?: unknown }).utf8;
      if (typeof utf8 === "string" && utf8.trim()) {
        chunks.push(decodeHtmlEntities(utf8));
      }
    }
  }

  if (chunks.length === 0) return null;
  return normalizeTranscriptText(chunks.join(" "));
}

function parseTranscriptFromXml(xml: string): string | null {
  const srv3Matches = xml.matchAll(/<p\b[^>]*>([\s\S]*?)<\/p>/g);
  const srv3Chunks: string[] = [];
  for (const match of srv3Matches) {
    const paragraph = match[1] || "";
    const segmentMatches = paragraph.matchAll(/<s\b[^>]*>([\s\S]*?)<\/s>/g);
    const segmentChunks: string[] = [];
    for (const segmentMatch of segmentMatches) {
      const value = segmentMatch[1] ? decodeHtmlEntities(segmentMatch[1]) : "";
      if (value.trim()) segmentChunks.push(value);
    }
    const fallback = paragraph.replace(/<[^>]+>/g, " ");
    const value = segmentChunks.length > 0 ? segmentChunks.join(" ") : fallback;
    if (value.trim()) srv3Chunks.push(value);
  }
  if (srv3Chunks.length > 0) {
    return normalizeTranscriptText(srv3Chunks.join(" "));
  }

  const matches = xml.matchAll(/<text\b[^>]*>([\s\S]*?)<\/text>/g);
  const chunks: string[] = [];
  for (const match of matches) {
    const value = match[1] ? decodeHtmlEntities(match[1]) : "";
    if (value.trim()) chunks.push(value);
  }
  if (chunks.length === 0) return null;
  return normalizeTranscriptText(chunks.join(" "));
}

function appendFmtJson3(url: string): string {
  if (url.includes("fmt=json3")) return url;
  return `${url}${url.includes("?") ? "&" : "?"}fmt=json3`;
}

function stripFmtJson3(url: string): string {
  return url
    .replace(/([?&])fmt=json3(&?)/, (_, prefix: string, suffix: string) =>
      suffix ? prefix : ""
    )
    .replace(/[?&]$/, "");
}

async function fetchTranscriptFromTrack(
  track: CaptionTrack
): Promise<
  | { ok: true; text: string; languageCode: string | null }
  | { ok: false; code: "transcript_fetch_failed" | "transcript_parse_failed" }
> {
  if (!track.baseUrl) {
    return { ok: false, code: "transcript_fetch_failed" };
  }

  const jsonResponse = await fetchJson(appendFmtJson3(track.baseUrl));
  if (jsonResponse.ok) {
    const parsed = parseTranscriptFromJson3(jsonResponse.data);
    if (parsed) {
      logTranscriptDebug("caption_track.json_success", {
        languageCode: track.languageCode,
        isAutoGenerated: track.isAutoGenerated,
        textLength: parsed.length,
      });
      return { ok: true, text: parsed, languageCode: track.languageCode };
    }
    logTranscriptDebug("caption_track.json_parse_failed", {
      languageCode: track.languageCode,
      isAutoGenerated: track.isAutoGenerated,
    });
  }

  const xmlResponse = await fetchText(stripFmtJson3(track.baseUrl));
  if (!xmlResponse.ok) {
    return { ok: false, code: "transcript_fetch_failed" };
  }

  const parsedXml = parseTranscriptFromXml(xmlResponse.text);
  if (!parsedXml) {
    logTranscriptDebug("caption_track.xml_parse_failed", {
      languageCode: track.languageCode,
      isAutoGenerated: track.isAutoGenerated,
      textLength: xmlResponse.text.length,
    });
    return { ok: false, code: "transcript_parse_failed" };
  }

  logTranscriptDebug("caption_track.xml_success", {
    languageCode: track.languageCode,
    isAutoGenerated: track.isAutoGenerated,
    textLength: parsedXml.length,
  });
  return { ok: true, text: parsedXml, languageCode: track.languageCode };
}

function buildTimedTextFallbacks(videoId: string): CaptionTrack[] {
  const urls = [
    { lang: "en", kind: "manual", url: `https://www.youtube.com/api/timedtext?v=${videoId}&lang=en` },
    { lang: "en-US", kind: "manual", url: `https://www.youtube.com/api/timedtext?v=${videoId}&lang=en-US` },
    { lang: "en", kind: "asr", url: `https://www.youtube.com/api/timedtext?v=${videoId}&lang=en&kind=asr` },
    { lang: "en", kind: "manual", url: `https://www.youtube.com/api/timedtext?v=${videoId}&lang=en&fmt=srv3` },
    { lang: "en", kind: "asr", url: `https://www.youtube.com/api/timedtext?v=${videoId}&lang=en&kind=asr&fmt=srv3` },
    { lang: "en", kind: "manual", url: `https://video.google.com/timedtext?v=${videoId}&lang=en` },
    { lang: "en-US", kind: "manual", url: `https://video.google.com/timedtext?v=${videoId}&lang=en-US` },
  ];

  return urls.map((entry) => ({
    baseUrl: entry.url,
    languageCode: entry.lang,
    isAutoGenerated: entry.kind === "asr",
  }));
}

async function fetchTranscriptViaInnertube(
  videoId: string,
  diagnostics: TranscriptDiagnostic[]
): Promise<TranscriptFetchResult> {
  for (const client of INNERTUBE_CLIENTS) {
    try {
      const response = await fetch(
        "https://www.youtube.com/youtubei/v1/player?prettyPrint=false",
        {
          method: "POST",
          cache: "no-store",
          headers: withYouTubeHeaders(client.headers, {
            "Content-Type": "application/json",
            Accept: "application/json,text/plain,*/*",
          }),
          body: JSON.stringify({
            context: client.context,
            videoId,
          }),
        }
      );

      if (!response.ok) {
        logTranscriptDebug("innertube.http_failed", {
          videoId,
          client: client.label,
          status: response.status,
        });
        diagnostics.push({
          code: "transcript_fetch_failed",
          message: `${client.label} returned HTTP ${response.status}.`,
        });
        continue;
      }

      const data = (await response.json()) as unknown;
      const status = findPlayabilityStatusInObject(data);
      if (status) {
        const rawStatus =
          typeof status.status === "string" ? status.status.toLowerCase() : "";
        const reason = typeof status.reason === "string" ? status.reason : "";
        if (rawStatus && rawStatus !== "ok") {
          logTranscriptDebug("innertube.unsupported_video", {
            videoId,
            client: client.label,
            status: rawStatus,
            reason,
          });
          diagnostics.push({
            code: "unsupported_video",
            message: `${client.label} playability status: ${rawStatus} ${reason}`.trim(),
          });
          return { ok: false, reason: "unsupported_video" };
        }
      }

      const tracks = normalizeCaptionTracks(findCaptionTracksInObject(data));
      if (tracks.length === 0) {
        logTranscriptDebug("innertube.no_tracks", {
          videoId,
          client: client.label,
        });
        diagnostics.push({
          code: "no_captions",
          message: `${client.label} did not expose caption tracks.`,
        });
        continue;
      }

      for (const track of prioritizeTracks(tracks)) {
        const transcript = await fetchTranscriptFromTrack(track);
        if (transcript.ok) {
          logTranscriptDebug("innertube.success", {
            videoId,
            client: client.label,
            languageCode: transcript.languageCode,
            textLength: transcript.text.length,
          });
          return {
            ok: true,
            text: transcript.text,
            languageCode: transcript.languageCode,
          };
        }
      }
      logTranscriptDebug("innertube.tracks_exhausted", {
        videoId,
        client: client.label,
        trackCount: tracks.length,
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : "unknown error";
      logTranscriptDebug("innertube.failed", {
        videoId,
        client: client.label,
        message,
      });
      diagnostics.push({
        code: "transcript_fetch_failed",
        message: `${client.label} failed: ${message}`,
      });
    }
  }

  logTranscriptDebug("innertube.exhausted", { videoId });
  return { ok: false, reason: "no_captions" };
}

async function fetchTranscriptViaCustomExtractor(
  videoId: string,
  diagnostics: TranscriptDiagnostic[]
): Promise<TranscriptFetchResult> {
  const watchHtml = await fetchWatchPage(videoId);
  if (!watchHtml) {
    diagnostics.push({
      code: "watch_page_fetch_failed",
      message: "Could not fetch YouTube watch page.",
    });
  } else {
    const watchFailure = classifyWatchHtmlFailure(watchHtml);
    if (watchFailure) {
      logTranscriptDebug("custom.watch_failure", {
        videoId,
        reason: watchFailure,
      });
      diagnostics.push({
        code:
          watchFailure === "unsupported_video"
            ? "unsupported_video"
            : "transcript_fetch_failed",
        message: `Watch page indicates ${watchFailure}.`,
      });
      return { ok: false, reason: watchFailure };
    }
  }

  const parsedTracks = watchHtml ? parseCaptionTracksFromWatchHtml(watchHtml) : [];
  if (parsedTracks.length === 0) {
    logTranscriptDebug("custom.no_watch_tracks", { videoId });
    diagnostics.push({
      code: "no_captions",
      message: "No caption tracks were discovered in watch page payloads.",
    });
  } else {
    logTranscriptDebug("custom.watch_tracks_found", {
      videoId,
      trackCount: parsedTracks.length,
    });
  }

  const candidateTracks = [
    ...prioritizeTracks(parsedTracks),
    ...prioritizeTracks(buildTimedTextFallbacks(videoId)),
  ];

  const seenTrackUrls = new Set<string>();
  const uniqueTracks = candidateTracks.filter((track) => {
    if (!track.baseUrl) return false;
    if (seenTrackUrls.has(track.baseUrl)) return false;
    seenTrackUrls.add(track.baseUrl);
    return true;
  });

  if (uniqueTracks.length === 0) {
    logTranscriptDebug("custom.no_candidate_tracks", { videoId });
    diagnostics.push({
      code: "transcript_url_missing",
      message: "No transcript URL candidates were available.",
    });
    diagnostics.push({
      code: "custom_extractor_failed",
      message: "Custom extractor had no usable transcript URL candidates.",
    });
    return { ok: false, reason: "no_captions" };
  }

  let sawFetchFailure = false;
  let sawParseFailure = false;

  for (const track of uniqueTracks) {
    const transcript = await fetchTranscriptFromTrack(track);
    if (transcript.ok) {
      logTranscriptDebug("custom.success", {
        videoId,
        languageCode: transcript.languageCode,
        textLength: transcript.text.length,
      });
      return {
        ok: true,
        text: transcript.text,
        languageCode: transcript.languageCode,
      };
    }

    if (transcript.code === "transcript_fetch_failed") {
      sawFetchFailure = true;
    }
    if (transcript.code === "transcript_parse_failed") {
      sawParseFailure = true;
    }
  }

  if (sawFetchFailure) {
    diagnostics.push({
      code: "transcript_fetch_failed",
      message: "Transcript track requests failed in custom extractor.",
    });
  }

  if (sawParseFailure) {
    diagnostics.push({
      code: "transcript_parse_failed",
      message: "Transcript payloads were fetched but could not be parsed.",
    });
  }

  diagnostics.push({
    code: "custom_extractor_failed",
    message: "Custom extractor did not resolve a usable transcript.",
  });
  logTranscriptDebug("custom.exhausted", {
    videoId,
    trackCount: uniqueTracks.length,
    sawFetchFailure,
    sawParseFailure,
  });

  if (sawFetchFailure && !sawParseFailure) {
    return { ok: false, reason: "transcript_fetch_failed" };
  }

  return { ok: false, reason: "unknown_error" };
}

function getTranscriptFailureMessage(reason: TranscriptFailureReason): string {
  switch (reason) {
    case "invalid_url":
      return "Please enter a valid YouTube URL.";
    case "no_captions":
      return "This video does not expose captions that we can read. Paste the transcript below to continue.";
    case "captions_disabled":
      return "Captions are disabled for this video. Paste the transcript below to continue.";
    case "unsupported_video":
      return "We can’t read captions from this video. It may be private, age-restricted, or unavailable. Paste the transcript below to continue.";
    case "transcript_fetch_failed":
      return "We couldn’t retrieve the captions from YouTube right now. Try again, or paste the transcript below to continue.";
    case "unknown_error":
    default:
      return "We couldn’t extract the transcript for this video. Paste the transcript below to continue.";
  }
}

function chooseFailureReason(
  diagnostics: TranscriptDiagnostic[],
  results: TranscriptFetchResult[]
): Exclude<TranscriptFailureReason, "invalid_url"> {
  const explicit = results
    .map((result) => (!result.ok ? result.reason : undefined))
    .filter((reason): reason is Exclude<TranscriptFailureReason, "invalid_url"> =>
      Boolean(reason)
    );

  for (const reason of [
    "unsupported_video",
    "captions_disabled",
    "transcript_fetch_failed",
    "no_captions",
    "unknown_error",
  ] as const) {
    if (explicit.includes(reason)) {
      return reason;
    }
  }

  if (diagnostics.some((item) => item.code === "unsupported_video")) {
    return "unsupported_video";
  }
  if (diagnostics.some((item) => item.code === "captions_disabled")) {
    return "captions_disabled";
  }
  if (
    diagnostics.some((item) =>
      ["watch_page_fetch_failed", "transcript_fetch_failed"].includes(item.code)
    )
  ) {
    return "transcript_fetch_failed";
  }
  if (
    diagnostics.some((item) =>
      ["no_captions", "caption_tracks_missing", "transcript_url_missing"].includes(
        item.code
      )
    )
  ) {
    return "no_captions";
  }

  return "unknown_error";
}

export async function fetchYouTubeTranscriptSource(
  sourceUrl: string
): Promise<YouTubeTranscriptResult> {
  const diagnostics: TranscriptDiagnostic[] = [];

  const parsed = parseYouTubeVideoIdDetailed(sourceUrl);
  if (!parsed.ok) {
    logTranscriptDebug("url.invalid", {
      reason: parsed.code,
    });
    diagnostics.push({
      code: mapUrlParseError(parsed.code),
      message: `URL parse failure: ${parsed.code}`,
    });

    return {
      ok: false,
      reason: "invalid_url",
      message: "Please enter a valid YouTube URL.",
      diagnostics,
    };
  }

  const { videoId } = parsed;
  logTranscriptDebug("pipeline.start", { videoId });

  // --- Strategy 1: Supadata ---
  const supadataResult = await fetchTranscriptViaSupadata(videoId, diagnostics);
  if (supadataResult.ok) {
    logTranscriptDebug("pipeline.success", {
      videoId,
      strategy: "supadata",
      languageCode: supadataResult.languageCode,
      textLength: supadataResult.text.length,
    });
    return {
      ok: true,
      videoId,
      sourceText: supadataResult.text,
      languageCode: supadataResult.languageCode,
      diagnostics,
    };
  }

  const libraryResult = await fetchTranscriptViaLibrary(videoId, diagnostics);
  if (libraryResult.ok) {
    logTranscriptDebug("pipeline.success", {
      videoId,
      strategy: "library",
      languageCode: libraryResult.languageCode,
      textLength: libraryResult.text.length,
    });
    return {
      ok: true,
      videoId,
      sourceText: libraryResult.text,
      languageCode: libraryResult.languageCode,
      diagnostics,
    };
  }

  const innertubeResult = await fetchTranscriptViaInnertube(videoId, diagnostics);
  if (innertubeResult.ok) {
    logTranscriptDebug("pipeline.success", {
      videoId,
      strategy: "innertube",
      languageCode: innertubeResult.languageCode,
      textLength: innertubeResult.text.length,
    });
    return {
      ok: true,
      videoId,
      sourceText: innertubeResult.text,
      languageCode: innertubeResult.languageCode,
      diagnostics,
    };
  }

  const customResult = await fetchTranscriptViaCustomExtractor(videoId, diagnostics);
  if (customResult.ok) {
    logTranscriptDebug("pipeline.success", {
      videoId,
      strategy: "custom",
      languageCode: customResult.languageCode,
      textLength: customResult.text.length,
    });
    return {
      ok: true,
      videoId,
      sourceText: customResult.text,
      languageCode: customResult.languageCode,
      diagnostics,
    };
  }

  const reason = chooseFailureReason(diagnostics, [
    supadataResult,
    libraryResult,
    innertubeResult,
    customResult,
  ]);
  logTranscriptDebug("pipeline.failed", {
    videoId,
    reason,
    diagnostics: diagnostics.map((item) => `${item.code}: ${item.message}`),
  });

  return {
    ok: false,
    reason,
    message: getTranscriptFailureMessage(reason),
    videoId,
    diagnostics,
  };
}
