// Langslate Corporate runtime metadata. Generated by
// scripts/langslate-migration/build-manifest.mjs from the Sept 10 client
// delivery; lesson HTML itself lives in external storage (see
// lib/langslateContent.ts). No fs/path here — metadata only — and nothing
// in this module depends on the main app shell, so it can move unchanged to
// a standalone langslatecorporate.com app (set the base path to "").
import catalogData from "./generated/langslateCorporateCatalog.json";

export const LANGSLATE_CORPORATE_BASE_PATH = "/apps/corporate";

export type CorporateLesson = {
  slug: string;
  title: string;
  number: number | null;
  contentKey: string;
};

export type CorporateCategory = {
  slug: string;
  label: string;
  lessons: CorporateLesson[];
};

export type CorporateFamilySlug = "industries" | "departments" | "pro" | "professions";

export type CorporateFamily = {
  slug: CorporateFamilySlug;
  label: string;
  categories: CorporateCategory[];
};

type CorporateCatalog = {
  version: number;
  product: "corporate";
  families: CorporateFamily[];
};

const catalog = catalogData as CorporateCatalog;

/** Client-facing copy per family; unit = what one lesson is called there. */
export const CORPORATE_FAMILY_COPY: Record<
  CorporateFamilySlug,
  { description: string; categoryNoun: string; categoryNounPlural: string; lessonNoun: string; lessonNounPlural: string }
> = {
  industries: {
    description: "Business English for the sector you work in.",
    categoryNoun: "industry",
    categoryNounPlural: "industries",
    lessonNoun: "lesson",
    lessonNounPlural: "lessons",
  },
  departments: {
    description: "The language of each team and function inside a company.",
    categoryNoun: "department",
    categoryNounPlural: "departments",
    lessonNoun: "lesson",
    lessonNounPlural: "lessons",
  },
  pro: {
    description: "Specialized professional programs, module by module.",
    categoryNoun: "program",
    categoryNounPlural: "programs",
    lessonNoun: "module",
    lessonNounPlural: "modules",
  },
  professions: {
    description: "Role-specific English for your profession.",
    categoryNoun: "profession",
    categoryNounPlural: "professions",
    lessonNoun: "lesson",
    lessonNounPlural: "lessons",
  },
};

export function listCorporateFamilies(): CorporateFamily[] {
  return catalog.families;
}

export function getCorporateFamily(slug: string): CorporateFamily | null {
  return catalog.families.find((family) => family.slug === slug) ?? null;
}

export function getCorporateCategory(
  familySlug: string,
  categorySlug: string
): { family: CorporateFamily; category: CorporateCategory } | null {
  const family = getCorporateFamily(familySlug);
  const category = family?.categories.find((c) => c.slug === categorySlug);
  return family && category ? { family, category } : null;
}

export function getCorporateLesson(
  familySlug: string,
  categorySlug: string,
  lessonSlug: string
): {
  family: CorporateFamily;
  category: CorporateCategory;
  lesson: CorporateLesson;
  previous: CorporateLesson | null;
  next: CorporateLesson | null;
} | null {
  const found = getCorporateCategory(familySlug, categorySlug);
  if (!found) return null;
  const index = found.category.lessons.findIndex((l) => l.slug === lessonSlug);
  if (index < 0) return null;
  const { lessons } = found.category;
  return {
    ...found,
    lesson: lessons[index],
    previous: lessons[index - 1] ?? null,
    next: lessons[index + 1] ?? null,
  };
}

export function countCorporateLessons(family: CorporateFamily): number {
  return family.categories.reduce((sum, category) => sum + category.lessons.length, 0);
}

export function corporateFamilyHref(familySlug: string): string {
  return `${LANGSLATE_CORPORATE_BASE_PATH}/${familySlug}`;
}

export function corporateCategoryHref(familySlug: string, categorySlug: string): string {
  return `${corporateFamilyHref(familySlug)}/${categorySlug}`;
}

export function corporateLessonHref(familySlug: string, categorySlug: string, lessonSlug: string): string {
  return `${corporateCategoryHref(familySlug, categorySlug)}/${lessonSlug}`;
}

export function corporateCategoryThumbnailSrc(familySlug: string, categorySlug: string): string {
  return `/corporate-thumbnails/${familySlug}/${familySlug}__${categorySlug}.webp`;
}
