// Langslate Academy runtime metadata. Generated by
// scripts/langslate-migration/build-manifest.mjs from the Sept 10 client
// delivery; lesson HTML itself lives in external storage (see
// lib/langslateContent.ts). This module is metadata only.
import catalogData from "./generated/langslateAcademyCatalog.json";
import { buildLangslateContentUrl } from "./langslateContent";

export const LANGSLATE_ACADEMY_BASE_PATH = "/apps/academy";

export type AcademyLevelSlug = "a0" | "a1" | "a2" | "b1" | "b2" | "c1";
export type AcademyLevelLabel = "A0" | "A1" | "A2" | "B1" | "B2" | "C1";

export type AcademyLesson = {
  slug: string;
  title: string;
  module?: number;
  number: number | null;
  contentKey: string;
};

export type AcademyLevel = {
  slug: AcademyLevelSlug;
  label: AcademyLevelLabel;
  lessons: AcademyLesson[];
};

type AcademyCatalog = {
  version: number;
  product: "academy";
  levels: AcademyLevel[];
};

export type AcademyRuntimeLesson = AcademyLesson & {
  id: number;
  level: AcademyLevelLabel;
  levelSlug: AcademyLevelSlug;
  contentUrl: string | null;
  xp: number;
  difficulty: number;
  duration: number;
};

export type AcademyRuntimeLevel = Omit<AcademyLevel, "lessons"> & {
  lessons: AcademyRuntimeLesson[];
};

const catalog = catalogData as AcademyCatalog;

const levelDifficulty: Record<AcademyLevelLabel, number> = {
  A0: 1,
  A1: 1,
  A2: 2,
  B1: 3,
  B2: 4,
  C1: 5,
};

const levelXp: Record<AcademyLevelLabel, number> = {
  A0: 8,
  A1: 10,
  A2: 14,
  B1: 18,
  B2: 24,
  C1: 30,
};

const levelDuration: Record<AcademyLevelLabel, number> = {
  A0: 10,
  A1: 14,
  A2: 18,
  B1: 24,
  B2: 30,
  C1: 36,
};

export const ACADEMY_LEVEL_ORDER: AcademyLevelLabel[] = ["A0", "A1", "A2", "B1", "B2", "C1"];

export function listAcademyLevels(): AcademyLevel[] {
  return catalog.levels;
}

export function countAcademyLessons(): number {
  return catalog.levels.reduce((sum, level) => sum + level.lessons.length, 0);
}

export function getAcademyLevel(slugOrLabel: string): AcademyLevel | null {
  const normalized = slugOrLabel.toLowerCase();
  return catalog.levels.find((level) => level.slug === normalized || level.label.toLowerCase() === normalized) ?? null;
}

export function listAcademyRuntimeLevels(baseUrl: string | null): AcademyRuntimeLevel[] {
  let id = 1;
  return catalog.levels.map((level) => ({
    ...level,
    lessons: level.lessons.map((lesson) => {
      const runtimeLesson: AcademyRuntimeLesson = {
        ...lesson,
        id,
        level: level.label,
        levelSlug: level.slug,
        contentUrl: buildLangslateContentUrl(lesson.contentKey, baseUrl),
        xp: levelXp[level.label],
        difficulty: levelDifficulty[level.label],
        duration: lesson.number ? Math.max(8, levelDuration[level.label] + (lesson.number % 5) - 2) : levelDuration[level.label],
      };
      id += 1;
      return runtimeLesson;
    }),
  }));
}

export function academyLevelHref(levelSlug: string): string {
  return `${LANGSLATE_ACADEMY_BASE_PATH}#courses/${levelSlug.toUpperCase()}`;
}
